apiVersion: v1
kind: Pod
metadata:
  namespace: debug-tools
  name: devspace
  labels:
    app: devspace
spec:
  containers:
  - image: loribao/devspace
    command:
      - "tail"
      - "-f" 
      - "/var/log/apt/history.log"
    imagePullPolicy: IfNotPresent
    name: devspace
  restartPolicy: Always
